//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSathi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FutureSathiEntities : DbContext
    {
        public FutureSathiEntities()
            : base("name=FutureSathiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAge> tblAges { get; set; }
        public virtual DbSet<tblBodyType> tblBodyTypes { get; set; }
        public virtual DbSet<tblChat> tblChats { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblComplextion> tblComplextions { get; set; }
        public virtual DbSet<tblDiet> tblDiets { get; set; }
        public virtual DbSet<tblEducation> tblEducations { get; set; }
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblHeight> tblHeights { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblMaritalStatu> tblMaritalStatus { get; set; }
        public virtual DbSet<tblProfession> tblProfessions { get; set; }
        public virtual DbSet<tblReligion> tblReligions { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblSubscription> tblSubscriptions { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWishList> tblWishLists { get; set; }
    }
}
