//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSathi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RoutValues { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
