//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSathi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblChats = new HashSet<tblChat>();
            this.tblChats1 = new HashSet<tblChat>();
            this.tblWishLists = new HashSet<tblWishList>();
        }
    
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Gender_id { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Looking_for_id { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age_id { get; set; }
        public Nullable<int> Religion_id { get; set; }
        public Nullable<int> Education_id { get; set; }
        public Nullable<int> Marital_Status_id { get; set; }
        public Nullable<int> Profession_id { get; set; }
        public Nullable<int> Income_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> State_id { get; set; }
        public Nullable<int> Height_id { get; set; }
        public Nullable<int> Body_Type_id { get; set; }
        public Nullable<int> Diet_id { get; set; }
        public Nullable<int> Complextion_id { get; set; }
        public Nullable<bool> Smoke_id { get; set; }
        public Nullable<bool> Drink_id { get; set; }
        public string Bio { get; set; }
        public string Photo_1 { get; set; }
        public string Photo_2 { get; set; }
        public string Photo_3 { get; set; }
        public string Family { get; set; }
        public Nullable<int> Subcription_id { get; set; }
    
        public virtual tblAge tblAge { get; set; }
        public virtual tblBodyType tblBodyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChat> tblChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChat> tblChats1 { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblComplextion tblComplextion { get; set; }
        public virtual tblDiet tblDiet { get; set; }
        public virtual tblEducation tblEducation { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblHeight tblHeight { get; set; }
        public virtual tblIncome tblIncome { get; set; }
        public virtual tblMaritalStatu tblMaritalStatu { get; set; }
        public virtual tblProfession tblProfession { get; set; }
        public virtual tblReligion tblReligion { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblSubscription tblSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWishList> tblWishLists { get; set; }
    }
}
