//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSathi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWishList
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Age_id { get; set; }
        public string Marital_Status { get; set; }
        public string Religion { get; set; }
        public string Education { get; set; }
        public string Diet { get; set; }
        public string Smoke { get; set; }
        public string Drink { get; set; }
        public string Body_Type { get; set; }
        public string Comlextion { get; set; }
        public string Profession { get; set; }
        public string State { get; set; }
        public Nullable<int> Income_id { get; set; }
        public Nullable<int> Height_id { get; set; }
    
        public virtual tblAge tblAge { get; set; }
        public virtual tblHeight tblHeight { get; set; }
        public virtual tblIncome tblIncome { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
